%ISOSPLIT5_MEX - 
%
% Syntax:  [labels_out] = isosplit5_mex(X)
%
% Inputs:
%    X - double (M,N)
%
% Outputs:
%    labels_out - double (1,N)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
